export const data = JSON.parse("{\"key\":\"v-d77ac87a\",\"path\":\"/notes/tech/%E4%BA%86%E8%A7%A3%E4%B8%80%E4%B8%8BESLint.html\",\"title\":\"了解一下ESLint\",\"lang\":\"zh-CN\",\"frontmatter\":{\"title\":\"了解一下ESLint\",\"icon\":\"article\",\"isOriginal\":true,\"date\":\"2022-07-26T00:00:00.000Z\",\"category\":[\"学习笔记\",\"前端\"],\"tag\":[\"前端\",\"工具\",\"javascript\"],\"image\":\"\",\"banner\":\"\",\"summary\":\"ESLint 究极基础。看了一天的视频，依然只学了个皮毛。\\n\",\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"https://vuepress-theme-hope-v2-demo.mrhope.site/notes/tech/%E4%BA%86%E8%A7%A3%E4%B8%80%E4%B8%8BESLint.html\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"企鹅反应堆\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"了解一下ESLint\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"zh-CN\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"前端\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"工具\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"javascript\"}],[\"meta\",{\"property\":\"article:published_time\",\"content\":\"2022-07-26T00:00:00.000Z\"}]]},\"excerpt\":\"<p>ESLint 究极基础。看了一天的视频，依然只学了个皮毛。</p>\\n\",\"headers\":[{\"level\":2,\"title\":\"作用\",\"slug\":\"作用\",\"children\":[]},{\"level\":2,\"title\":\"包\",\"slug\":\"包\",\"children\":[]},{\"level\":2,\"title\":\"初始化\",\"slug\":\"初始化\",\"children\":[{\"level\":3,\"title\":\"创建目录\",\"slug\":\"创建目录\",\"children\":[]},{\"level\":3,\"title\":\"ESLint 安装\",\"slug\":\"eslint-安装\",\"children\":[]},{\"level\":3,\"title\":\"生成 ESLint 配置文件\",\"slug\":\"生成-eslint-配置文件\",\"children\":[]}]},{\"level\":2,\"title\":\"进行语法检查\",\"slug\":\"进行语法检查\",\"children\":[]},{\"level\":2,\"title\":\"配置文件\",\"slug\":\"配置文件\",\"children\":[{\"level\":3,\"title\":\"globals 节点\",\"slug\":\"globals-节点\",\"children\":[]},{\"level\":3,\"title\":\"env 节点\",\"slug\":\"env-节点\",\"children\":[]},{\"level\":3,\"title\":\"extends 节点\",\"slug\":\"extends-节点\",\"children\":[]},{\"level\":3,\"title\":\"parserOptions 节点\",\"slug\":\"parseroptions-节点\",\"children\":[]},{\"level\":3,\"title\":\"rules 节点\",\"slug\":\"rules-节点\",\"children\":[]}]},{\"level\":2,\"title\":\"检查语法的规则\",\"slug\":\"检查语法的规则\",\"children\":[{\"level\":3,\"title\":\"本质\",\"slug\":\"本质\",\"children\":[]},{\"level\":3,\"title\":\"ESLint 内置的语法规范\",\"slug\":\"eslint-内置的语法规范\",\"children\":[]},{\"level\":3,\"title\":\"自定义语法规范\",\"slug\":\"自定义语法规范\",\"children\":[]}]},{\"level\":2,\"title\":\"语法规范包类型\",\"slug\":\"语法规范包类型\",\"children\":[]},{\"level\":2,\"title\":\"如何与 Vue 一同使用\",\"slug\":\"如何与-vue-一同使用\",\"children\":[]},{\"level\":2,\"title\":\"如何使用 VSCode 扩展\",\"slug\":\"如何使用-vscode-扩展\",\"children\":[{\"level\":3,\"title\":\"安装\",\"slug\":\"安装\",\"children\":[]},{\"level\":3,\"title\":\"配置\",\"slug\":\"配置\",\"children\":[]}]}],\"readingTime\":{\"minutes\":4.91,\"words\":1472},\"filePathRelative\":\"notes/tech/了解一下ESLint.md\",\"localizedDate\":\"2022年7月26日\"}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
